"""
Newsletter writer.

Design choice made during hardening: the per-article factual sections
are rendered DETERMINISTICALLY in code from the structured fields the
summarizer already produced (agent/summarize.py), not re-generated by
an LLM here. This is a deliberate, stronger guarantee than "prompt the
LLM to follow grounding rules and hope" -- an ungrounded article's
section is built exclusively from the fixed fallback template and can
never contain LLM-invented text, because the LLM never sees it.

The LLM is used for exactly one thing: synthesizing the Editor's
Takeaway, and only from the subset of articles that are actually
grounded in real extracted content. If too few (or zero) articles are
grounded, the Editor's Takeaway is also generated deterministically
(see agent/grounding.DETERMINISTIC_EDITORS_TAKEAWAY) -- the LLM is
never given the chance to generalize a trend from title-only articles.
"""

from __future__ import annotations

from typing import Any

from agent.grounding import (
    DETERMINISTIC_EDITORS_TAKEAWAY,
    build_fallback_summary,
    build_llm_failed_summary,
)
from tools.llm_utils import get_llm, is_rate_limit_error, response_to_text

_TAKEAWAY_GROUNDING_RULES = """
SOURCE-GROUNDING RULES:
- Use only the supplied article content and structured summaries.
- Never infer factual claims from a title alone.
- If content is unavailable, preserve the deterministic fallback wording.
- Do not invent events, findings, announcements, recommendations, dates, numbers, or implications.
- Do not generalize a weekly trend from unsupported title-only articles.
- Clearly disclose source limitations.
"""


def _source_line(article: dict[str, Any]) -> str:
    """
    Deterministically renders the source line. The label is derived
    strictly from url_resolution_status (and, for the unresolved case,
    which provider it came from) -- the LLM never writes this line, so
    it can never falsely claim a verified source was found.
    """

    resolution_status = article.get("url_resolution_status", "unresolved")
    resolved_url = article.get("resolved_url", "")
    reference_url = article.get("rss_url") or article.get("url", "")
    provider = article.get("provider", "")

    if resolution_status == "verified_direct" and resolved_url:
        return f"**Source:** [Verified publisher article]({resolved_url})"

    if reference_url:
        provider_labels = {
            "google_news": "Google News reference",
            "bing_news": "Bing News reference",
        }
        label = provider_labels.get(provider, "Unverified reference")
        return f"**Source:** [{label}]({reference_url})"

    return "**Source:** Not available"


def render_article_section(index: int, article: dict[str, Any]) -> str:
    """Deterministically renders one article's Markdown section."""

    title = article.get("title") or "Untitled article"
    grounding_status = article.get("grounding_status")
    content_available = article.get("content_available", False)
    is_grounded = grounding_status == "grounded" and content_available
    # Content was genuinely extracted, but the LLM summarization call
    # itself failed (e.g. rate limit, malformed response) -- distinct
    # from an article whose content was never available at all.
    is_llm_failed_with_content = grounding_status == "error_fallback" and content_available

    if is_grounded:
        what_happened = article.get("what_happened") or "No details available."
        key_takeaways = article.get("key_takeaways") or ["No key takeaways available."]
        why_it_matters = article.get("why_it_matters") or "Relevance not specified."
        source_limitations = article.get("source_limitations") or "None noted."
    else:
        # Force one of the two deterministic fallback templates,
        # regardless of whatever (if anything) happens to already be on
        # the article -- this is the hard safety net against unsupported
        # claims. Which template applies is decided from the article's
        # actual, factual extraction state (content_available), never
        # from LLM-produced wording -- a "content available, LLM failed"
        # article must never be described as title-only, and vice versa.
        if is_llm_failed_with_content:
            fallback = build_llm_failed_summary(article)
        else:
            fallback = build_fallback_summary(article)
        what_happened = fallback["what_happened"]
        key_takeaways = fallback["key_takeaways"]
        why_it_matters = fallback["why_it_matters"]
        source_limitations = fallback["source_limitations"]

    takeaways_md = "\n".join(f"- {point}" for point in key_takeaways)

    return f"""## {index}. {title}

**What happened:**
{what_happened}

**Key takeaways:**
{takeaways_md}

**Why it matters:**
{why_it_matters}

**Source limitations:**
{source_limitations}

{_source_line(article)}
"""


def build_articles_context(articles: list[dict[str, Any]]) -> str:
    """
    Text context used by the reviser/critic LLM prompts. Reflects the
    same structured fields the summarizer produces.
    """

    if not articles:
        return "No articles are available."

    sections: list[str] = []

    for index, article in enumerate(articles, start=1):
        title = article.get("title") or "Untitled article"
        source = article.get("source") or "Unknown source"
        published = article.get("published") or ""
        grounding_status = article.get("grounding_status", "fallback")
        content_available = article.get("content_available", False)

        sections.append(
            f"""Article {index}
Title: {title}
Source: {source}
Published: {published}
Content available: {content_available}
Grounding status: {grounding_status}
What happened: {article.get("what_happened", "")}
Key takeaways: {article.get("key_takeaways", [])}
Why it matters: {article.get("why_it_matters", "")}
Source limitations: {article.get("source_limitations", "")}
"""
        )

    return "\n---\n\n".join(sections)


def build_editors_takeaway(goal: str, articles: list[dict[str, Any]]) -> str:
    """
    Synthesizes the Editor's Takeaway strictly from grounded articles.
    Falls back to a deterministic, limitation-disclosing paragraph when
    there isn't enough verified content to safely draw a conclusion
    from -- this is a hard threshold check in code, not a prompt
    instruction the LLM could ignore.
    """

    total = len(articles)
    grounded = [
        a for a in articles
        if a.get("grounding_status") == "grounded" and a.get("content_available", False)
    ]

    if total == 0 or not grounded or len(grounded) < max(1, total / 2):
        return DETERMINISTIC_EDITORS_TAKEAWAY

    context = "\n".join(
        f"- {a.get('title', 'Untitled')}: {a.get('what_happened', '')}"
        for a in grounded
    )

    prompt = f"""
You are an editor writing the closing "Editor's Takeaway" paragraph for
a newsletter about AI agents.
{_TAKEAWAY_GROUNDING_RULES}

Editorial goal:
{goal}

Write ONE short paragraph (3-4 sentences) synthesizing ONLY the
verified articles below. Do not reference or draw conclusions from any
article not listed here.

Verified articles:
{context}

Return only the paragraph text, no heading, no Markdown formatting.
"""

    try:
        llm = get_llm(max_tokens=400)
        response = llm.invoke(prompt)
        text = response_to_text(response).strip()

        if text:
            return text

    except Exception as exc:
        if is_rate_limit_error(exc):
            print(f"Groq rate limit/token limit reached while writing Editor's Takeaway: {exc}")
        else:
            print(f"Editor's Takeaway generation failed: {exc}")

    return DETERMINISTIC_EDITORS_TAKEAWAY


def _fallback_newsletter(goal: str, articles: list[dict[str, Any]]) -> str:
    """Used only when there are zero articles at all."""

    return (
        "# Weekly AI Agent Insights\n\n"
        f"**Goal:** {goal}\n\n"
        "No articles could be retrieved for this goal. Please try again "
        "later or broaden the newsletter goal.\n\n"
        "## Editor's Takeaway\n\n"
        "No source articles were available this week, so no content or "
        "conclusions can be reported.\n"
    )


def write_newsletter(goal: str, articles: list[dict[str, Any]]) -> str:
    """
    Builds the complete Markdown newsletter: deterministic per-article
    sections + an Editor's Takeaway that is either LLM-synthesized from
    verified content only, or deterministic when there isn't enough
    verified content to safely synthesize from.
    """

    if not articles:
        return _fallback_newsletter(goal, articles)

    sections = [
        render_article_section(index, article)
        for index, article in enumerate(articles, start=1)
    ]

    editors_takeaway = build_editors_takeaway(goal, articles)

    body = "\n---\n\n".join(sections)

    return (
        "# Weekly AI Agent Insights\n\n"
        f"{body}\n"
        "---\n\n"
        "## Editor's Takeaway\n\n"
        f"{editors_takeaway}\n"
    )


def writer_node(state: dict[str, Any]) -> dict[str, Any]:
    """LangGraph node for newsletter writing."""

    goal = state.get("goal", "Create a weekly AI-agent newsletter.")
    articles = state.get("ranked_articles") or state.get("raw_articles") or []

    draft_newsletter = write_newsletter(goal, articles)

    return {
        "draft_newsletter": draft_newsletter,
    }


if __name__ == "__main__":
    sample_articles = [
        {
            "title": "Example AI Agent Announcement",
            "source": "Example Source",
            "published": "2026-01-01",
            "url": "https://example.com/article",
            "resolved_url": "https://example.com/article",
            "url_resolution_status": "verified_direct",
            "content_available": True,
            "grounding_status": "grounded",
            "what_happened": "An AI-agent capability was announced.",
            "key_takeaways": [
                "The announcement focuses on AI-agent workflows.",
                "The capability may support task automation.",
            ],
            "why_it_matters": "It shows continued investment in agent tooling.",
            "source_limitations": "None noted.",
        }
    ]

    print(
        write_newsletter(
            "Create a weekly newsletter about important AI-agent developments.",
            sample_articles,
        )
    )
